language: node_js
sudo: false
node_js:
  - 0.10
env:
  - SLIMERJSLAUNCHER=$(which firefox) DISPLAY=:99.0 PATH=$TRAVIS_BUILD_DIR/slimerjs:$PATH
addons:
  firefox: "50.0"
branches:
  except:
    - gh-pages
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "echo 'Installing SlimerJS'"
  - "wget http://download.slimerjs.org/releases/0.10.2/slimerjs-0.10.2.zip"
  - "unzip slimerjs-0.10.2.zip"
  - "mv slimerjs-0.10.2 ./slimerjs"
  - "echo 'Installing Grunt'"
  - "npm install -g grunt-cli"
